name: Update Code on Server
on:
  push:
    branches: [master]

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_POS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.DO_POS_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Update Code on Server
        run: |
          ssh root@${{ secrets.DO_POS_SERVER_IP }} << 'EOF'
            cd /var/www/pos
            git reset --hard HEAD
            git clean -fd
            git pull origin master
          EOF
